children_child:
    resource: "@ChildrenChildBundle/Resources/config/routing.yml"
    prefix:   /
    
    
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin


