security:
    encoders:
        Children\ChildBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
        

    providers:
        main:
            entity: 
                class: Children\ChildBundle\Entity\User
                property: username




    firewalls:

        main:
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: true


    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: /, role: IS_AUTHENTICATED_ANONYMOUSLY }
