_security_login:
    pattern:  /login
    defaults: { _controller: ChildrenChildBundle:Security:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

admin_home:
    pattern:  /admin/
    defaults: { _controller: ChildrenChildBundle:Admin:index }


children_child_homepage:
    path:     /
    defaults: { _controller: ChildrenChildBundle:Default:index }
