Children\ChildBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        password:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        salt:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    manyToMany:
        userRoles:
            targetEntity: Children\ChildBundle\Entity\Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinTable:
                name: user_role
                schema: null
                joinColumns:
                    -
                        name: user_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: role_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
